
/*===========================================================================
 * Include file 
 *===========================================================================*/ 
#include "Customer_config.h"
 
#include "AHC_Menu.h"

#include "UI_DrawGeneral.h"
#include "IconDefine.h"
#include "IconPosition.h"
#include "MenuCommon.h"
#include "DrawStateVideoFunc.h"
#include "DrawStateCameraFunc.h"
#include "DrawStateBrowserFunc.h"
#include "DrawStateMoviePBFunc.h"
#include "DrawStatePhotoPBFunc.h"
#include "DrawStateSlideShowFunc.h"
#include "DrawStateTVFunc.h"
#include "DrawStateHdmiFunc.h"
#include "DrawStateMenuSetting.h"

/*===========================================================================
 * Global variable
 *===========================================================================*/

#ifndef _OEM_DRAW_ //Use Default Drawing Set

UI_DARW_SET m_VideoDraw[] =
{
	{VIDEO_GUI_MOVIE_RES, 	POS_ICON_MOVIE_RES_X, 	POS_ICON_MOVIE_RES_Y, 	AHC_TRUE , OSDDrawSetting_MovieSize},
	{VIDEO_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{VIDEO_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{VIDEO_GUI_WB_MODE	, 	POS_ICON_WB_MODE_X, 	POS_ICON_WB_MODE_Y, 	AHC_TRUE , OSDDrawSetting_WB_Mode},
	{VIDEO_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{VIDEO_GUI_SCENE	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{VIDEO_GUI_FLASH	, 	POS_ICON_FLASHLIGHT_X, 	POS_ICON_FLASHLIGHT_Y, 	AHC_TRUE , DrawVideoRecFlashMode},
	{VIDEO_GUI_REC_STATE, 	POS_VIDEO_STATE_X, 		POS_VIDEO_STATE_Y,		AHC_TRUE , DrawVideoRecStatus},
	{VIDEO_GUI_ZOOM_BAR	, 	POS_ZOOM_BAR_X, 		POS_ZOOM_BAR_Y, 		AHC_TRUE , DrawVideoZoomBar},	
	{VIDEO_GUI_EV		, 	POS_ICON_EV_X, 			POS_ICON_EV_Y, 			AHC_TRUE , OSDDrawSetting_EV},
	{VIDEO_GUI_REMAIN_TIME, POS_VIDEO_REMAIN_TIME_X,POS_VIDEO_REMAIN_TIME_Y,AHC_TRUE , DrawVideoAvailableRecordTime},
	{VIDEO_GUI_REC_TIME	, 	POS_VIDEO_REC_TIME_X, 	POS_VIDEO_REC_TIME_Y, 	AHC_TRUE , DrawVideoCurrentRecordTime},
	{VIDEO_GUI_RTC_TIME	, 	POS_VIDEO_RTC_TIME_X, 	POS_VIDEO_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{VIDEO_GUI_LOCK_FILE, 	POS_VIDEO_LOCK_FILE_X, 	POS_VIDEO_LOCK_FILE_Y, 	AHC_TRUE , DrawVideoLockFileStatus},
	{VIDEO_GUI_LOCK_NUM , 	POS_VIDEO_LOCK_NUM_X, 	POS_VIDEO_LOCK_NUM_Y, 	AHC_TRUE , DrawVideoLockFileNum},
	{VIDEO_GUI_MUTE		, 	POS_VIDEO_MUTE_X, 		POS_VIDEO_MUTE_Y, 		AHC_TRUE , DrawVideoMuteRecord},
	{VIDEO_GUI_REC_POINT, 	POS_VIDEO_REC_POINT_X, 	POS_VIDEO_REC_POINT_Y, 	AHC_TRUE,  DrawVideoRecording},
	{VIDEO_GUI_GPS_STATE, 	POS_GPS_STATE_X, 		POS_GPS_STATE_Y, 		AHC_TRUE , OSDDraw_GPSStatus},
	{VIDEO_GUI_VMD_STATE, 	POS_ICON_VMD_X, 		POS_ICON_VMD_Y, 		AHC_TRUE , DrawVideoMotionDtc},
	{VIDEO_GUI_VTL_STATE, 	POS_ICON_VTL_X, 		POS_ICON_VTL_Y, 		AHC_TRUE , DrawVideoTimeLapse},		// VIDEO_REC_TIMELAPSE_EN
	{VIDEO_GUI_DRIVER_ID, 	POS_DRIVER_ID_X, 		POS_DRIVER_ID_Y, 		AHC_TRUE , OSDDrawSetting_DriverId},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
	{VIDEO_GUI_WIFI,		POS_ICON_WIFI_X, 		POS_ICON_WIFI_Y, 		AHC_TRUE , DrawVideoWiFi},
	{VIDEO_GUI_WIFI_SWITCH, POS_ICON_WIFI_SWITCH_X, POS_ICON_WIFI_SWITCH_Y, AHC_TRUE , DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
	{VIDEO_GUI_LDWS_LINE,	0,						0,						AHC_TRUE,  DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
	{VIDEO_GUI_FCWS_INFO,	0,						0,						AHC_TRUE,  DrawVideoFCWS_Info},
#endif
	{VIDEO_GUI_MAX		,   0,						0,						AHC_FALSE, NULL},
	{AUDIO_GUI_REC_TIME, 	POS_VIDEO_REC_TIME_X, 	POS_VIDEO_REC_TIME_Y, 	AHC_TRUE , DrawAudioCurRecordTime},
	{AUDIO_GUI_REC_POINT, 	POS_VIDEO_REC_POINT_X, 	POS_VIDEO_REC_POINT_Y, 	AHC_TRUE , DrawAudioRecording},
	{0xFFFF}
};

#if (DSC_MODE_ENABLE)
UI_DARW_SET m_DSCDraw[] = 
{
	{DSC_GUI_IMAGE_RES	, 	POS_ICON_IMAGE_RES_X, 	POS_ICON_IMAGE_RES_Y, 	AHC_TRUE , OSDDrawSetting_ImageSize},
	{DSC_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{DSC_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{DSC_GUI_WB_MODE	, 	POS_ICON_WB_MODE_X, 	POS_ICON_WB_MODE_Y, 	AHC_TRUE , OSDDrawSetting_WB_Mode},
	{DSC_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{DSC_GUI_SCENE		, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{DSC_GUI_FLASH		, 	POS_ICON_FLASHLIGHT_X, 	POS_ICON_FLASHLIGHT_Y, 	AHC_TRUE , DrawCaptureFlashMode},
	{DSC_GUI_SELF_TIMER , 	POS_ICON_SELFTIMER_X, 	POS_ICON_SELFTIMER_Y,	AHC_TRUE , OSDDrawSetting_SelfTimer},
	{DSC_GUI_BURST		, 	POS_ICON_BURST_X, 		POS_ICON_BURST_Y,		AHC_TRUE , OSDDrawSetting_BurstShot},
	{DSC_GUI_ZOOM_BAR	, 	POS_ZOOM_BAR_X, 		POS_ZOOM_BAR_Y, 		AHC_TRUE , DrawCaptureZoomBar},
	{DSC_GUI_EV			, 	POS_ICON_EV_X, 			POS_ICON_EV_Y, 			AHC_TRUE , OSDDrawSetting_EV},
	{DSC_GUI_REMAIN_NUM	, 	POS_DSC_REMAIN_NUM_X,	POS_DSC_REMAIN_NUM_Y,	AHC_TRUE , DrawCaptureRemainNum},
	{DSC_GUI_RTC_TIME	, 	POS_VIDEO_RTC_TIME_X, 	POS_VIDEO_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{DSC_GUI_GPS_STATE  , 	POS_GPS_STATE_X, 		POS_GPS_STATE_Y, 		AHC_FALSE, OSDDraw_GPSStatus},
	{DSC_GUI_VMD_STATE  , 	POS_ICON_VMD_X, 		POS_ICON_VMD_Y, 		AHC_FALSE , DrawCaptureMotionDtc},
	{DSC_GUI_DRIVER_ID  , 	POS_DRIVER_ID_X, 		POS_DRIVER_ID_Y, 		AHC_TRUE , OSDDrawSetting_DriverId},
	{0xFFFF}
};
#endif

UI_DARW_SET m_BrowserDraw[] = 
{
	{BROWSER_GUI_FILENAME	, 		POS_BROW_FILENAME_X, 	POS_BROW_FILENAME_Y, 	AHC_TRUE , DrawBrowser_NameInfo},
	{BROWSER_GUI_UI_MODE	, 		POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{BROWSER_GUI_SD_STATE	, 		POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{BROWSER_GUI_BATTERY	, 		POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{BROWSER_GUI_FILE_DATE 	, 		POS_BROW_FILEDATE_X, 	POS_BROW_FILEDATE_Y,	AHC_TRUE , DrawBrowser_DateInfo},
	{BROWSER_GUI_MOV_TOTAL_TIME	, 	POS_BROW_TOTAL_TIME_X, 	POS_BROW_TOTAL_TIME_Y,	AHC_TRUE , DrawBrowser_TotalTime},
#if defined(POS_BROW_RESOLUTION_SHOW)&& POS_BROW_RESOLUTION_SHOW
    {BROWSER_GUI_RESOLUTION	, 	    POS_BROW_RESOLUTION_X, 	POS_BROW_RESOLUTION_Y,	AHC_TRUE , DrawBrowser_ResolutionInfo},
#endif
	{0xFFFF}
};

UI_DARW_SET m_MovPBDraw[] = 
{
	{MOVPB_GUI_STATUS, 		POS_MOVPB_STATUS_X, 	POS_MOVPB_STATUS_Y, 	AHC_TRUE , DrawMovPb_Status},
	{MOVPB_GUI_FILE_INDEX, 	POS_MOVPB_FILE_IDX_X, 	POS_MOVPB_FILE_IDX_Y, 	AHC_TRUE , DrawMovPb_FileIndex},
	{MOVPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{MOVPB_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{MOVPB_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{MOVPB_GUI_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, NULL}, // TBD
	{MOVPB_GUI_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 	POS_MOVPB_LOCK_FILE_Y, 	AHC_TRUE , DrawMovPb_LockCurFile},
	{MOVPB_GUI_FILENAME , 	POS_MOVPB_FILENAME_X, 	POS_MOVPB_FILENAME_Y,	AHC_TRUE , DrawMovPb_FileInfo},
	{MOVPB_GUI_CUR_TIME	, 	POS_MOVPB_CUR_TIME_X, 	POS_MOVPB_CUR_TIME_Y,	AHC_TRUE , DrawMovPb_PlayInfo},
	{MOVPB_GUI_TOTAL_TIME, 	POS_MOVPB_TOTAL_TIME_X, POS_MOVPB_TOTAL_TIME_Y, AHC_TRUE , DrawMovPb_TotalTime},
	{0xFFFF}
};

#if (AUDIO_REC_PLAY_EN)
UI_DARW_SET m_AudPBDraw[] = 
{
	{AUDPB_GUI_STATUS, 		POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE,  DrawAudPb_Status},
	{AUDPB_GUI_FILE_INDEX, 	POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_TRUE,  DrawAudPb_FileIndex},
	{AUDPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE,  OSDDrawSetting_UIMode},
	{AUDPB_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE,  OSDDrawSetting_MediaType},
	{AUDPB_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE,  OSDDrawSetting_BatteryStatus},
	{AUDPB_GUI_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, NULL}, // TBD
	{AUDPB_GUI_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_TRUE,  DrawAudPb_LockCurFile},
	{AUDPB_GUI_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE,  DrawAudPb_FileInfo},
	{AUDPB_GUI_CUR_TIME	, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE,  DrawAudPb_PlayInfo},
	{AUDPB_GUI_TOTAL_TIME, 	POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE,  DrawAudPb_TotalTime},
	{0xFFFF}
};
#endif

UI_DARW_SET m_JpgPBDraw[] = 
{
	{JPGPB_GUI_FILE_INDEX, 	POS_JPGPB_FILE_IDX_X, 	POS_JPGPB_FILE_IDX_Y, 	AHC_TRUE , DrawJpgPb_FileIndex},
	{JPGPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{JPGPB_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{JPGPB_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{JPGPB_GUI_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 	POS_JPGPB_LOCK_FILE_Y, 	AHC_TRUE , DrawJpgPb_LockCurFile},
	{JPGPB_GUI_FILENAME , 	POS_JPGPB_FILENAME_X, 	POS_JPGPB_FILENAME_Y,	AHC_TRUE , DrawJpgPb_FileInfo},		
	{JPGPB_GUI_FILEDATE, 	POS_JPGPB_FILEDATE_X, 	POS_JPGPB_FILEDATE_Y,	AHC_TRUE , DrawJpgPb_DateInfo},
	{0xFFFF}
};

#if (SLIDESHOW_EN)
UI_DARW_SET m_SlideDraw[] = 
{
	{SLIDE_GUI_STATUS, 		POS_SLIDE_MOVPB_STATUS_X, 	POS_SLIDE_MOVPB_STATUS_Y, 	AHC_TRUE , DrawSlideShow_MovPbState},
	{SLIDE_GUI_FILE_INDEX, 	POS_SLIDE_FILE_IDX_X, 	  	POS_SLIDE_FILE_IDX_Y, 		AHC_TRUE , DrawSlideShow_FileIndex},
	{SLIDE_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 		POS_ICON_UI_MODE_Y, 		AHC_TRUE , OSDDrawSetting_UIMode},
	{SLIDE_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 			POS_ICON_MEDIA_Y, 			AHC_TRUE , OSDDrawSetting_MediaType},
	{SLIDE_GUI_BATTERY	, 	POS_ICON_BATT_X, 			POS_ICON_BATT_Y, 			AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{SLIDE_GUI_LOCK_FILE, 	POS_SLIDE_LOCK_FILE_X, 		POS_SLIDE_LOCK_FILE_Y, 		AHC_TRUE , DrawSlideShow_LockCurFile},
	{SLIDE_GUI_CUR_TIME	, 	POS_SLIDE_MOV_CUR_TIME_X, 	POS_SLIDE_MOV_CUR_TIME_Y,	AHC_TRUE , DrawSlideShow_MovPlayInfo},
	{SLIDE_GUI_TOTAL_TIME, 	POS_SLIDE_MOV_TOTAL_TIME_X, POS_SLIDE_MOV_TOTAL_TIME_Y, AHC_TRUE , DrawSlideShow_MovTotalTime},
	{0xFFFF}
};
#endif

/*===========================================================================
 * Global variable : TV Drawing
 *===========================================================================*/

#if (TVOUT_ENABLE)

#if (TVOUT_PREVIEW_EN)
UI_DARW_SET m_TVVideoDraw[] = 
{
	{TV_GUI_VIDEO_MOVIE_RES	, 	POS_ICON_TV_MOVIE_RES_X, 	POS_ICON_TV_MOVIE_RES_Y, 	AHC_TRUE , OSDDrawSetting_MovieSize},
	{TV_GUI_VIDEO_UI_MODE	, 	POS_ICON_TV_UI_MODE_X, 		POS_ICON_TV_UI_MODE_Y, 		AHC_TRUE , OSDDrawSetting_UIMode},
	{TV_GUI_VIDEO_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 		POS_ICON_TV_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{TV_GUI_VIDEO_WB_MODE	, 	POS_ICON_TV_WB_MODE_X, 		POS_ICON_TV_WB_MODE_Y, 		AHC_TRUE , OSDDrawSetting_WB_Mode},
	{TV_GUI_VIDEO_BATTERY	, 	POS_ICON_TV_BATT_X, 		POS_ICON_TV_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{TV_GUI_VIDEO_SCENE		, 	POS_ICON_TV_SCENE_X, 		POS_ICON_TV_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{TV_GUI_VIDEO_FLASH		, 	POS_ICON_TV_FLASHLIGHT_X, 	POS_ICON_TV_FLASHLIGHT_Y, 	AHC_TRUE , DrawVideoRecFlashMode},
	{TV_GUI_VIDEO_REC_STATE	, 	POS_VIDEO_TV_STATE_X, 		POS_VIDEO_TV_STATE_Y,		AHC_TRUE , DrawVideoRecStatus},
	{TV_GUI_VIDEO_ZOOM_BAR	, 	POS_TV_ZOOM_BAR_X, 			POS_TV_ZOOM_BAR_Y, 			AHC_TRUE , DrawVideoZoomBar},
	{TV_GUI_VIDEO_EV		, 	POS_ICON_TV_EV_X, 			POS_ICON_TV_EV_Y, 			AHC_TRUE , OSDDrawSetting_EV},
	{TV_GUI_VIDEO_REMAIN_TIME, 	POS_VIDEO_TV_REMAIN_TIME_X,	POS_VIDEO_TV_REMAIN_TIME_Y,	AHC_TRUE , DrawVideoAvailableRecordTime},
	{TV_GUI_VIDEO_REC_TIME	, 	POS_VIDEO_TV_REC_TIME_X, 	POS_VIDEO_TV_REC_TIME_Y, 	AHC_TRUE , DrawVideoCurrentRecordTime},
	{TV_GUI_VIDEO_RTC_TIME	, 	POS_VIDEO_TV_RTC_TIME_X, 	POS_VIDEO_TV_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{TV_GUI_VIDEO_LOCK_FILE	, 	POS_VIDEO_TV_LOCK_FILE_X, 	POS_VIDEO_TV_LOCK_FILE_Y, 	AHC_TRUE , DrawVideoLockFileStatus},
	{TV_GUI_VIDEO_LOCK_NUM	, 	POS_VIDEO_TV_LOCK_NUM_X, 	POS_VIDEO_TV_LOCK_NUM_Y, 	AHC_FALSE, DrawVideoLockFileNum},
	{TV_GUI_VIDEO_MUTE		, 	POS_VIDEO_TV_MUTE_X, 		POS_VIDEO_TV_MUTE_Y, 		AHC_TRUE , DrawVideoMuteRecord},
	{TV_GUI_VIDEO_REC_POINT	, 	POS_VIDEO_TV_REC_POINT_X, 	POS_VIDEO_TV_REC_POINT_Y, 	AHC_TRUE , DrawVideoRecording},
	{TV_GUI_VIDEO_GPS_STATE	, 	POS_TV_GPS_STATE_X, 		POS_TV_GPS_STATE_Y, 		AHC_TRUE , OSDDraw_GPSStatus},
	{TV_GUI_VIDEO_VMD_STATE , 	POS_ICON_TV_VMD_X, 			POS_ICON_TV_VMD_Y, 			AHC_TRUE , DrawVideoMotionDtc},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
	{TV_GUI_VIDEO_WIFI,		    POS_ICON_TV_WIFI_X, 		POS_ICON_TV_WIFI_Y,         AHC_TRUE , DrawVideoWiFi},
	{TV_GUI_VIDEO_WIFI_SWITCH,  POS_ICON_TV_WIFI_SWITCH_X,  POS_ICON_TV_WIFI_SWITCH_Y,  AHC_TRUE , DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
	{TV_GUI_VIDEO_GUI_LDWS_LINE,0,							0,							AHC_TRUE,  DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
	{TV_GUI_VIDEO_GUI_FCWS_INFO,0,							0,							AHC_TRUE,  DrawVideoFCWS_Info},
#endif
	{TV_GUI_VIDEO_MAX		,   0,							0,							AHC_FALSE, NULL},
	{TV_GUI_AUDIO_REC_TIME  , 	POS_VIDEO_TV_REC_TIME_X, 	POS_VIDEO_TV_REC_TIME_Y, 	AHC_TRUE , DrawAudioCurRecordTime},
	{TV_GUI_AUDIO_REC_POINT , 	POS_VIDEO_TV_REC_POINT_X, 	POS_VIDEO_TV_REC_POINT_Y, 	AHC_TRUE , DrawAudioRecording},
	{0xFFFF}
};

#if (DSC_MODE_ENABLE)
UI_DARW_SET m_TVDSCDraw[] = 
{
	{TV_GUI_DSC_IMAGE_RES	, 	POS_ICON_TV_IMAGE_RES_X, 	POS_ICON_TV_IMAGE_RES_Y, 	AHC_TRUE , OSDDrawSetting_ImageSize},
	{TV_GUI_DSC_UI_MODE		, 	POS_ICON_TV_UI_MODE_X, 		POS_ICON_TV_UI_MODE_Y, 		AHC_TRUE , OSDDrawSetting_UIMode},
	{TV_GUI_DSC_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 		POS_ICON_TV_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{TV_GUI_DSC_WB_MODE		, 	POS_ICON_TV_WB_MODE_X, 		POS_ICON_TV_WB_MODE_Y, 		AHC_TRUE , OSDDrawSetting_WB_Mode},
	{TV_GUI_DSC_BATTERY		, 	POS_ICON_TV_BATT_X, 		POS_ICON_TV_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{TV_GUI_DSC_SCENE		, 	POS_ICON_TV_SCENE_X, 		POS_ICON_TV_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{TV_GUI_DSC_FLASH		, 	POS_ICON_TV_FLASHLIGHT_X, 	POS_ICON_TV_FLASHLIGHT_Y, 	AHC_TRUE , DrawCaptureFlashMode},
	{TV_GUI_DSC_SELF_TIMER , 	POS_ICON_TV_SELFTIMER_X, 	POS_ICON_TV_SELFTIMER_Y,	AHC_TRUE , OSDDrawSetting_SelfTimer},
	{TV_GUI_DSC_BURST		, 	POS_ICON_TV_BURST_X, 		POS_ICON_TV_BURST_Y,		AHC_TRUE , OSDDrawSetting_BurstShot},
	{TV_GUI_DSC_ZOOM_BAR	, 	POS_TV_ZOOM_BAR_X, 			POS_TV_ZOOM_BAR_Y, 			AHC_TRUE,  DrawCaptureZoomBar},
	{TV_GUI_DSC_EV			, 	POS_ICON_TV_EV_X, 			POS_ICON_TV_EV_Y, 			AHC_TRUE , OSDDrawSetting_EV},
	{TV_GUI_DSC_REMAIN_NUM	, 	POS_DSC_TV_REMAIN_NUM_X,	POS_DSC_TV_REMAIN_NUM_Y,	AHC_TRUE , DrawCaptureRemainNum},
	{TV_GUI_DSC_RTC_TIME	, 	POS_VIDEO_TV_RTC_TIME_X, 	POS_VIDEO_TV_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{TV_GUI_DSC_GPS_STATE	, 	POS_TV_GPS_STATE_X, 		POS_TV_GPS_STATE_Y, 		AHC_FALSE , OSDDraw_GPSStatus},
	{TV_GUI_DSC_VMD_STATE	, 	POS_ICON_TV_VMD_X, 			POS_ICON_TV_VMD_Y, 			AHC_TRUE , DrawCaptureMotionDtc},
	{0xFFFF}
};
#endif
#endif

UI_DARW_SET m_TVMovPBDraw[] = 
{
	{TV_GUI_MOVPB_STATUS, 		POS_TV_MOV_STATE_X, 	POS_TV_MOV_STATE_Y, 	AHC_TRUE , DrawTVMoviePB_Status},
	{TV_GUI_MOVPB_FILE_INDEX, 	POS_TV_MOV_FILEIDX_X, 	POS_TV_MOV_FILEIDX_Y, 	AHC_TRUE , DrawTVMoviePB_FileIndex},
	{TV_GUI_MOVPB_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_FALSE, OSDDrawSetting_UIMode},
	{TV_GUI_MOVPB_SD_STATE	, 	POS_ICON_TV_MEDIA_X,    POS_ICON_TV_MEDIA_Y, 	AHC_FALSE, OSDDrawSetting_MediaType},
	{TV_GUI_MOVPB_BATTERY	, 	POS_ICON_TV_BATT_X,		POS_ICON_TV_BATT_Y,		AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{TV_GUI_MOVPB_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, NULL}, // TBD
	{TV_GUI_MOVPB_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 	POS_MOVPB_LOCK_FILE_Y, 	AHC_FALSE ,DrawMovPb_LockCurFile},
	{TV_GUI_MOVPB_FILENAME , 	POS_TV_MOV_NAME_X, 		POS_TV_MOV_NAME_Y,		AHC_TRUE , DrawTVMoviePB_NameInfo},
	{TV_GUI_MOVPB_CUR_TIME	, 	POS_TV_MOV_CURTIME_X, 	POS_TV_MOV_CURTIME_Y,	AHC_TRUE , DrawTVMoviePB_PlayInfo},
	{TV_GUI_MOVPB_TOTAL_TIME, 	POS_TV_MOV_TOTALTIME_X, POS_TV_MOV_TOTALTIME_Y, AHC_TRUE , DrawTVMoviePB_TotalTime},
	{0xFFFF}
};

#if (AUDIO_REC_PLAY_EN)
UI_DARW_SET m_TVAudPBDraw[] = 
{
	{TV_GUI_AUDPB_STATUS, 		POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE,  DrawAudPb_Status},
	{TV_GUI_AUDPB_FILE_INDEX, 	POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_FALSE, DrawAudPb_FileIndex},
	{TV_GUI_AUDPB_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_FALSE, OSDDrawSetting_UIMode},
	{TV_GUI_AUDPB_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 	POS_ICON_TV_MEDIA_Y,	AHC_FALSE, OSDDrawSetting_MediaType},
	{TV_GUI_AUDPB_BATTERY	, 	POS_ICON_TV_BATT_X,		POS_ICON_TV_BATT_Y,		AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{TV_GUI_AUDPB_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, NULL},
	{TV_GUI_AUDPB_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_FALSE, DrawAudPb_LockCurFile},
	{TV_GUI_AUDPB_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE,  DrawAudPb_FileInfo},
	{TV_GUI_AUDPB_CUR_TIME	, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE,  DrawAudPb_PlayInfo},
	{TV_GUI_AUDPB_TOTAL_TIME, 	POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE,  DrawAudPb_TotalTime},
	{0xFFFF}
};
#endif

UI_DARW_SET m_TVJpgPBDraw[] = 
{
	{TV_GUI_JPGPB_FILE_INDEX, 	POS_TV_JPG_FILEIDX_X, 	POS_TV_JPG_FILEIDX_Y, 	AHC_TRUE,  DrawTVPhotoPB_FileIndex},
	{TV_GUI_JPGPB_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_FALSE, OSDDrawSetting_UIMode},
	{TV_GUI_JPGPB_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 	POS_ICON_TV_MEDIA_Y,	AHC_FALSE, OSDDrawSetting_MediaType},
	{TV_GUI_JPGPB_BATTERY	, 	POS_ICON_TV_BATT_X,		POS_ICON_TV_BATT_Y,		AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{TV_GUI_JPGPB_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 	POS_JPGPB_LOCK_FILE_Y, 	AHC_FALSE, DrawJpgPb_LockCurFile},
	{TV_GUI_JPGPB_FILENAME , 	POS_TV_JPG_NAME_X, 		POS_TV_JPG_NAME_Y,		AHC_TRUE , DrawTVPhotoPB_NameInfo},
	{TV_GUI_JPGPB_FILEDATE , 	POS_TV_JPG_FILEDATE_X, 	POS_TV_JPG_FILEDATE_Y,	AHC_TRUE , DrawTVPhotoPB_DateInfo},
	{0xFFFF}
};

#endif // #if (TVOUT_ENABLE)

/*===========================================================================
 * Global variable : HDMI Drawing
 *===========================================================================*/

#if (HDMI_ENABLE)

#if (HDMI_PREVIEW_EN)
UI_DARW_SET m_HdmiVideoDraw_1080P[] = 
{
	{HDMI_GUI_VIDEO_MOVIE_RES	, 	POS_ICON_HDMI_1080P_MOVIE_RES_X, 		POS_ICON_HDMI_1080P_MOVIE_RES_Y, 	AHC_TRUE , OSDDrawSetting_MovieSize},
	{HDMI_GUI_VIDEO_UI_MODE		, 	POS_ICON_HDMI_1080P_UI_MODE_X, 		POS_ICON_HDMI_1080P_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{HDMI_GUI_VIDEO_SD_STATE	, 	POS_ICON_HDMI_1080P_MEDIA_X, 			POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{HDMI_GUI_VIDEO_WB_MODE		, 	POS_ICON_HDMI_1080P_WB_MODE_X, 		POS_ICON_HDMI_1080P_WB_MODE_Y, 	AHC_TRUE , OSDDrawSetting_WB_Mode},
	{HDMI_GUI_VIDEO_BATTERY		, 	POS_ICON_HDMI_1080P_BATT_X, 			POS_ICON_HDMI_1080P_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_VIDEO_SCENE		, 	POS_ICON_HDMI_1080P_SCENE_X, 			POS_ICON_HDMI_1080P_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{HDMI_GUI_VIDEO_FLASH		, 	POS_ICON_HDMI_1080P_FLASHLIGHT_X, 	POS_ICON_HDMI_1080P_FLASHLIGHT_Y, AHC_TRUE , DrawVideoRecFlashMode},
	{HDMI_GUI_VIDEO_REC_STATE	, 	POS_ICON_HDMI_1080P_STATE_X, 		POS_ICON_HDMI_1080P_STATE_Y,		AHC_TRUE , DrawVideoRecStatus},
	{HDMI_GUI_VIDEO_ZOOM_BAR	, 	POS_ICON_HDMI_1080P_ZOOM_BAR_X, 	POS_ICON_HDMI_1080P_ZOOM_BAR_Y, 		AHC_TRUE , DrawVideoZoomBar},
	{HDMI_GUI_VIDEO_EV			, 	POS_ICON_HDMI_1080P_EV_X, 			POS_ICON_HDMI_1080P_EV_Y, 		AHC_TRUE , OSDDrawSetting_EV},
	{HDMI_GUI_VIDEO_REMAIN_TIME, 	POS_ICON_HDMI_1080P_REMAIN_TIME_X,	POS_ICON_HDMI_1080P_REMAIN_TIME_Y,AHC_TRUE, DrawVideoAvailableRecordTime},
	{HDMI_GUI_VIDEO_REC_TIME	, 	POS_ICON_HDMI_1080P_REC_TIME_X, 		POS_ICON_HDMI_1080P_REC_TIME_Y, 	AHC_TRUE , DrawVideoCurrentRecordTime},
	{HDMI_GUI_VIDEO_RTC_TIME	, 	POS_ICON_HDMI_1080P_RTC_TIME_X, 		POS_ICON_HDMI_1080P_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{HDMI_GUI_VIDEO_LOCK_FILE	, 	POS_ICON_HDMI_1080P_LOCK_FILE_X, 	POS_ICON_HDMI_1080P_LOCK_FILE_Y, AHC_TRUE , DrawVideoLockFileStatus},
	{HDMI_GUI_VIDEO_LOCK_NUM	, 	POS_ICON_HDMI_1080P_LOCK_NUM_X, 		POS_ICON_HDMI_1080P_LOCK_NUM_Y, 	AHC_FALSE, DrawVideoLockFileNum},
	{HDMI_GUI_VIDEO_MUTE		, 	POS_ICON_HDMI_1080P_MUTE_X, 			POS_ICON_HDMI_1080P_MUTE_Y, 		AHC_TRUE , DrawVideoMuteRecord},
	{HDMI_GUI_VIDEO_REC_POINT	, 	POS_ICON_HDMI_1080P_REC_POINT_X, 	POS_ICON_HDMI_1080P_REC_POINT_Y, AHC_TRUE , DrawVideoRecording},
	{HDMI_GUI_VIDEO_GPS_STATE	, 	POS_ICON_HDMI_1080P_GPS_STATE_X, 			POS_ICON_HDMI_1080P_GPS_STATE_Y, 		AHC_TRUE , OSDDraw_GPSStatus},
	{HDMI_GUI_VIDEO_VMD_STATE 	, 	POS_ICON_HDMI_1080P_VMD_X, 			POS_ICON_HDMI_1080P_VMD_Y, 		AHC_TRUE , DrawVideoMotionDtc},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
//	{HDMI_GUI_VIDEO_WIFI,		    POS_ICON_TV_WIFI_X, 		    POS_ICON_HDMI_WIFI_Y,       AHC_TRUE , DrawVideoWiFi},
//	{HDMI_GUI_VIDEO_WIFI_SWITCH,    POS_ICON_TV_WIFI_SWITCH_X,      POS_ICON_HDMI_WIFI_SWITCH_Y,AHC_TRUE , DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
//	{HDMI_GUI_VIDEO_GUI_LDWS_LINE,  0,  							0,							AHC_TRUE,  DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
//	{HDMI_GUI_VIDEO_GUI_FCWS_INFO,  0,							    0,							AHC_TRUE,  DrawVideoFCWS_Info},
#endif
	{HDMI_GUI_VIDEO_MAX			,   0,								0,							AHC_FALSE, NULL},
	{HDMI_GUI_AUDIO_REC_TIME  , 	POS_ICON_HDMI_1080P_REC_TIME_X, 		POS_ICON_HDMI_1080P_REC_TIME_Y, 	AHC_TRUE , DrawAudioCurRecordTime},
	{HDMI_GUI_AUDIO_REC_POINT , 	POS_ICON_HDMI_1080P_REC_POINT_X, 	POS_ICON_HDMI_1080P_REC_POINT_Y, AHC_TRUE , DrawAudioRecording},
	{0xFFFF}
};

#if (DSC_MODE_ENABLE)
UI_DARW_SET m_HdmiDSCDraw_1080P[] = 
{
	{HDMI_GUI_DSC_IMAGE_RES	, 	POS_ICON_HDMI_1080P_IMAGE_RES_X, 	POS_ICON_HDMI_1080P_IMAGE_RES_Y, 	AHC_TRUE , OSDDrawSetting_ImageSize},
	{HDMI_GUI_DSC_UI_MODE	,	POS_ICON_HDMI_1080P_UI_MODE_X, 	POS_ICON_HDMI_1080P_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{HDMI_GUI_DSC_SD_STATE	, 	POS_ICON_HDMI_1080P_MEDIA_X, 		POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{HDMI_GUI_DSC_WB_MODE	, 	POS_ICON_HDMI_1080P_WB_MODE_X, 	POS_ICON_HDMI_1080P_WB_MODE_Y, 	AHC_TRUE , OSDDrawSetting_WB_Mode},
	{HDMI_GUI_DSC_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 		POS_ICON_HDMI_1080P_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_DSC_SCENE		, 	POS_ICON_HDMI_1080P_SCENE_X, 		POS_ICON_HDMI_1080P_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{HDMI_GUI_DSC_FLASH		, 	POS_ICON_HDMI_1080P_FLASHLIGHT_X, POS_ICON_HDMI_1080P_FLASHLIGHT_Y, AHC_TRUE , DrawCaptureFlashMode},
	{HDMI_GUI_DSC_SELF_TIMER, 	POS_ICON_HDMI_1080P_SELFTIMER_X, 	POS_ICON_HDMI_1080P_SELFTIMER_Y,	AHC_TRUE , OSDDrawSetting_SelfTimer},
	{HDMI_GUI_DSC_BURST		, 	POS_ICON_HDMI_1080P_BURST_X, 		POS_ICON_HDMI_1080P_BURST_Y,		AHC_TRUE , OSDDrawSetting_BurstShot},
	{HDMI_GUI_DSC_ZOOM_BAR	, 	POS_ICON_HDMI_1080P_ZOOM_BAR_X, 		POS_ICON_HDMI_1080P_ZOOM_BAR_Y, 		AHC_TRUE , DrawCaptureZoomBar},
	{HDMI_GUI_DSC_EV		, 	POS_ICON_HDMI_1080P_EV_X, 		POS_ICON_HDMI_1080P_EV_Y, 		AHC_TRUE , OSDDrawSetting_EV},
	{HDMI_GUI_DSC_REMAIN_NUM, 	POS_ICON_HDMI_1080P_REMAIN_NUM_X,	POS_ICON_HDMI_1080P_REMAIN_NUM_Y,	AHC_TRUE , DrawCaptureRemainNum},
	{HDMI_GUI_DSC_RTC_TIME	, 	POS_ICON_HDMI_1080P_RTC_TIME_X, 	POS_ICON_HDMI_1080P_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{HDMI_GUI_DSC_GPS_STATE	, 	POS_ICON_HDMI_1080P_GPS_STATE_X, 		POS_ICON_HDMI_1080P_GPS_STATE_Y, 		AHC_FALSE , OSDDraw_GPSStatus},
	{HDMI_GUI_DSC_VMD_STATE	, 	POS_ICON_HDMI_1080P_VMD_X, 		POS_ICON_HDMI_1080P_VMD_Y, 		AHC_TRUE , DrawCaptureMotionDtc},
	{0xFFFF}
};
#endif
#endif

UI_DARW_SET m_HdmiMovPBDraw_1080P[] = 
{
	{HDMI_GUI_MOVPB_STATUS, 	POS_ICON_HDMI_1080P_MOV_STATE_X, 		POS_ICON_HDMI_1080P_MOV_STATE_Y, 		AHC_TRUE , DrawHdmiMoviePB_Status},
	{HDMI_GUI_MOVPB_FILE_INDEX, POS_ICON_HDMI_1080P_MOV_FILEIDX_X, 	POS_ICON_HDMI_1080P_MOV_FILEIDX_Y, 	AHC_TRUE , DrawHdmiMoviePB_FileIndex},
	{HDMI_GUI_MOVPB_UI_MODE	, 	POS_ICON_HDMI_1080P_UI_MODE_X, 	POS_ICON_HDMI_1080P_UI_MODE_Y,	AHC_FALSE, OSDDrawSetting_UIMode},
	{HDMI_GUI_MOVPB_SD_STATE, 	POS_ICON_HDMI_1080P_MEDIA_X, 		POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_FALSE, OSDDrawSetting_MediaType},
	{HDMI_GUI_MOVPB_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 		POS_ICON_HDMI_1080P_BATT_Y, 		AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_MOVPB_VOL_BAR	, 	POS_ICON_HDMI_1080P_SCENE_X, 		POS_ICON_HDMI_1080P_SCENE_Y,		AHC_FALSE, NULL}, // TBD
	{HDMI_GUI_MOVPB_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 		POS_MOVPB_LOCK_FILE_Y, 		AHC_FALSE, DrawMovPb_LockCurFile},
	{HDMI_GUI_MOVPB_FILENAME , 	POS_ICON_HDMI_1080P_MOV_NAME_X, 		POS_ICON_HDMI_1080P_MOV_NAME_Y,		AHC_TRUE , DrawHdmiMoviePB_NameInfo},
	{HDMI_GUI_MOVPB_CUR_TIME, 	POS_ICON_HDMI_1080P_MOV_CURTIME_X, 	POS_ICON_HDMI_1080P_MOV_CURTIME_Y,		AHC_TRUE , DrawHdmiMoviePB_PlayInfo},
	{HDMI_GUI_MOVPB_TOTAL_TIME, POS_ICON_HDMI_1080P_MOV_TOTALTIME_X, 	POS_ICON_HDMI_1080P_MOV_TOTALTIME_Y, 	AHC_TRUE , DrawHdmiMoviePB_TotalTime},
	{0xFFFF}
};

#if (AUDIO_REC_PLAY_EN)
UI_DARW_SET m_HdmiAudPBDraw_1080P[] = 
{
	{HDMI_GUI_AUDPB_STATUS, 	POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE,  DrawAudPb_Status},
	{HDMI_GUI_AUDPB_FILE_INDEX, POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_FALSE, DrawAudPb_FileIndex},
	{HDMI_GUI_AUDPB_UI_MODE	, 	POS_ICON_HDMI_1080P_UI_MODE_X,POS_ICON_HDMI_1080P_UI_MODE_Y,AHC_FALSE, OSDDrawSetting_UIMode},
	{HDMI_GUI_AUDPB_SD_STATE, 	POS_ICON_HDMI_1080P_MEDIA_X, 	POS_ICON_HDMI_1080P_MEDIA_Y, 	AHC_FALSE, OSDDrawSetting_MediaType},
	{HDMI_GUI_AUDPB_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 	POS_ICON_HDMI_1080P_BATT_Y, 	AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_AUDPB_VOL_BAR	, 	POS_ICON_HDMI_1080P_SCENE_X, 	POS_ICON_HDMI_1080P_SCENE_Y,	AHC_FALSE, NULL},
	{HDMI_GUI_AUDPB_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_FALSE, DrawAudPb_LockCurFile},
	{HDMI_GUI_AUDPB_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE,  DrawAudPb_FileInfo},
	{HDMI_GUI_AUDPB_CUR_TIME, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE,  DrawAudPb_PlayInfo},
	{HDMI_GUI_AUDPB_TOTAL_TIME, POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE,  DrawAudPb_TotalTime},
	{0xFFFF}
};
#endif

UI_DARW_SET m_HdmiJpgPBDraw_1080P[] = 
{
	{HDMI_GUI_JPGPB_FILE_INDEX, POS_ICON_HDMI_1080P_JPG_FILEIDX_X, 	POS_ICON_HDMI_1080P_JPG_FILEIDX_Y, 	AHC_TRUE,  DrawHdmiPhotoPB_FileIndex},
	{HDMI_GUI_JPGPB_UI_MODE	, 	POS_ICON_HDMI_1080P_UI_MODE_X, 		POS_ICON_HDMI_1080P_UI_MODE_Y,	AHC_FALSE, OSDDrawSetting_UIMode},
	{HDMI_GUI_JPGPB_SD_STATE, 	POS_ICON_HDMI_1080P_MEDIA_X, 		POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_FALSE, OSDDrawSetting_MediaType},
	{HDMI_GUI_JPGPB_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 		POS_ICON_HDMI_1080P_BATT_Y, 		AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_JPGPB_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 				POS_JPGPB_LOCK_FILE_Y, 		AHC_FALSE, DrawJpgPb_LockCurFile},
	{HDMI_GUI_JPGPB_FILENAME , 	POS_ICON_HDMI_1080P_JPG_NAME_X, 		POS_ICON_HDMI_1080P_JPG_NAME_Y,		AHC_TRUE , DrawHdmiPhotoPB_NameInfo},
	{HDMI_GUI_JPGPB_FILEDATE , 	POS_ICON_HDMI_1080P_JPG_FILEDATE_X, 	POS_ICON_HDMI_1080P_JPG_FILEDATE_Y,	AHC_TRUE , DrawHdmiPhotoPB_DateInfo},
	{0xFFFF}
};

////////////////////////////////////////////////////////////////////////////////////////////////
#if (HDMI_PREVIEW_EN)
UI_DARW_SET m_HdmiVideoDraw_720P[] = 
{
	{HDMI_GUI_VIDEO_MOVIE_RES	, 	POS_ICON_HDMI_720P_MOVIE_RES_X, 	POS_ICON_HDMI_720P_MOVIE_RES_Y, 	AHC_TRUE , OSDDrawSetting_MovieSize},
	{HDMI_GUI_VIDEO_UI_MODE		, 	POS_ICON_HDMI_720P_UI_MODE_X, 		POS_ICON_HDMI_720P_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{HDMI_GUI_VIDEO_SD_STATE	, 	POS_ICON_HDMI_720P_MEDIA_X, 		POS_ICON_HDMI_720P_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{HDMI_GUI_VIDEO_WB_MODE		, 	POS_ICON_HDMI_720P_WB_MODE_X, 		POS_ICON_HDMI_720P_WB_MODE_Y, 	AHC_TRUE , OSDDrawSetting_WB_Mode},
	{HDMI_GUI_VIDEO_BATTERY		, 	POS_ICON_HDMI_720P_BATT_X, 			POS_ICON_HDMI_720P_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_VIDEO_SCENE		, 	POS_ICON_HDMI_720P_SCENE_X, 		POS_ICON_HDMI_720P_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{HDMI_GUI_VIDEO_FLASH		, 	POS_ICON_HDMI_720P_FLASHLIGHT_X, 	POS_ICON_HDMI_720P_FLASHLIGHT_Y, AHC_TRUE , DrawVideoRecFlashMode},
	{HDMI_GUI_VIDEO_REC_STATE	, 	POS_ICON_HDMI_720P_STATE_X, 		POS_ICON_HDMI_720P_STATE_Y,		AHC_TRUE , DrawVideoRecStatus},
	{HDMI_GUI_VIDEO_ZOOM_BAR	, 	POS_ICON_HDMI_720P_ZOOM_BAR_X, 		POS_ICON_HDMI_720P_ZOOM_BAR_Y, 		AHC_TRUE , DrawVideoZoomBar},
	{HDMI_GUI_VIDEO_EV			, 	POS_ICON_HDMI_720P_EV_X, 			POS_ICON_HDMI_720P_EV_Y, 		AHC_TRUE , OSDDrawSetting_EV},
	{HDMI_GUI_VIDEO_REMAIN_TIME, 	POS_ICON_HDMI_720P_REMAIN_TIME_X,	POS_ICON_HDMI_720P_REMAIN_TIME_Y,AHC_TRUE, DrawVideoAvailableRecordTime},
	{HDMI_GUI_VIDEO_REC_TIME	, 	POS_ICON_HDMI_720P_REC_TIME_X, 		POS_ICON_HDMI_720P_REC_TIME_Y, 	AHC_TRUE , DrawVideoCurrentRecordTime},
	{HDMI_GUI_VIDEO_RTC_TIME	, 	POS_ICON_HDMI_720P_RTC_TIME_X, 		POS_ICON_HDMI_720P_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{HDMI_GUI_VIDEO_LOCK_FILE	, 	POS_ICON_HDMI_720P_LOCK_FILE_X, 	POS_ICON_HDMI_720P_LOCK_FILE_Y, AHC_TRUE , DrawVideoLockFileStatus},
	{HDMI_GUI_VIDEO_LOCK_NUM	, 	POS_ICON_HDMI_720P_LOCK_NUM_X, 		POS_ICON_HDMI_720P_LOCK_NUM_Y, 	AHC_FALSE, DrawVideoLockFileNum},
	{HDMI_GUI_VIDEO_MUTE		, 	POS_ICON_HDMI_720P_MUTE_X, 			POS_ICON_HDMI_720P_MUTE_Y, 		AHC_TRUE , DrawVideoMuteRecord},
	{HDMI_GUI_VIDEO_REC_POINT	, 	POS_ICON_HDMI_720P_REC_POINT_X, 	POS_ICON_HDMI_720P_REC_POINT_Y, AHC_TRUE , DrawVideoRecording},
	{HDMI_GUI_VIDEO_GPS_STATE	, 	POS_ICON_HDMI_720P_GPS_STATE_X, 	POS_ICON_HDMI_720P_GPS_STATE_Y, 		AHC_TRUE , OSDDraw_GPSStatus},
	{HDMI_GUI_VIDEO_VMD_STATE 	, 	POS_ICON_HDMI_720P_VMD_X, 			POS_ICON_HDMI_720P_VMD_Y, 		AHC_TRUE , DrawVideoMotionDtc},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
//	{HDMI_GUI_VIDEO_WIFI,		    POS_ICON_TV_WIFI_X, 		    POS_ICON_HDMI_720P_WIFI_Y,       AHC_TRUE , DrawVideoWiFi},
//	{HDMI_GUI_VIDEO_WIFI_SWITCH,    POS_ICON_TV_WIFI_SWITCH_X,      POS_ICON_HDMI_720P_WIFI_SWITCH_Y,AHC_TRUE , DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
//	{HDMI_GUI_VIDEO_GUI_LDWS_LINE,  0,  							0,							AHC_TRUE,  DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
//	{HDMI_GUI_VIDEO_GUI_FCWS_INFO,  0,							    0,							AHC_TRUE,  DrawVideoFCWS_Info},
#endif
	{HDMI_GUI_VIDEO_MAX			,   0,								0,							AHC_FALSE, NULL},
	{HDMI_GUI_AUDIO_REC_TIME  , 	POS_ICON_HDMI_720P_REC_TIME_X, 		POS_ICON_HDMI_720P_REC_TIME_Y, 	AHC_TRUE , DrawAudioCurRecordTime},
	{HDMI_GUI_AUDIO_REC_POINT , 	POS_ICON_HDMI_720P_REC_POINT_X, 	POS_ICON_HDMI_720P_REC_POINT_Y, AHC_TRUE , DrawAudioRecording},
	{0xFFFF}
};

#if (DSC_MODE_ENABLE)
UI_DARW_SET m_HdmiDSCDraw_720P[] = 
{
	{HDMI_GUI_DSC_IMAGE_RES	, 	POS_ICON_HDMI_720P_IMAGE_RES_X, 	POS_ICON_HDMI_720P_IMAGE_RES_Y, 	AHC_TRUE , OSDDrawSetting_ImageSize},
	{HDMI_GUI_DSC_UI_MODE	,	POS_ICON_HDMI_720P_UI_MODE_X, 	POS_ICON_HDMI_720P_UI_MODE_Y, 	AHC_TRUE , OSDDrawSetting_UIMode},
	{HDMI_GUI_DSC_SD_STATE	, 	POS_ICON_HDMI_720P_MEDIA_X, 		POS_ICON_HDMI_720P_MEDIA_Y, 		AHC_TRUE , OSDDrawSetting_MediaType},
	{HDMI_GUI_DSC_WB_MODE	, 	POS_ICON_HDMI_720P_WB_MODE_X, 	POS_ICON_HDMI_720P_WB_MODE_Y, 	AHC_TRUE , OSDDrawSetting_WB_Mode},
	{HDMI_GUI_DSC_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 		POS_ICON_HDMI_720P_BATT_Y, 		AHC_TRUE , OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_DSC_SCENE		, 	POS_ICON_HDMI_720P_SCENE_X, 		POS_ICON_HDMI_720P_SCENE_Y,	 	AHC_TRUE , OSDDrawSetting_SceneMode},
	{HDMI_GUI_DSC_FLASH		, 	POS_ICON_HDMI_720P_FLASHLIGHT_X, POS_ICON_HDMI_720P_FLASHLIGHT_Y, AHC_TRUE , DrawCaptureFlashMode},
	{HDMI_GUI_DSC_SELF_TIMER, 	POS_ICON_HDMI_720P_SELFTIMER_X, 	POS_ICON_HDMI_720P_SELFTIMER_Y,	AHC_TRUE , OSDDrawSetting_SelfTimer},
	{HDMI_GUI_DSC_BURST		, 	POS_ICON_HDMI_720P_BURST_X, 		POS_ICON_HDMI_720P_BURST_Y,		AHC_TRUE , OSDDrawSetting_BurstShot},
	{HDMI_GUI_DSC_ZOOM_BAR	, 	POS_ICON_HDMI_720P_ZOOM_BAR_X, 		POS_ICON_HDMI_720P_ZOOM_BAR_Y, 		AHC_TRUE , DrawCaptureZoomBar},
	{HDMI_GUI_DSC_EV		, 	POS_ICON_HDMI_720P_EV_X, 		POS_ICON_HDMI_720P_EV_Y, 		AHC_TRUE , OSDDrawSetting_EV},
	{HDMI_GUI_DSC_REMAIN_NUM, 	POS_ICON_HDMI_720P_REMAIN_NUM_X,	POS_ICON_HDMI_720P_REMAIN_NUM_Y,	AHC_TRUE , DrawCaptureRemainNum},
	{HDMI_GUI_DSC_RTC_TIME	, 	POS_ICON_HDMI_720P_RTC_TIME_X, 	POS_ICON_HDMI_720P_RTC_TIME_Y, 	AHC_TRUE , OSDDraw_CurrentRTCTime},
	{HDMI_GUI_DSC_GPS_STATE	, 	POS_ICON_HDMI_720P_GPS_STATE_X, 		POS_ICON_HDMI_720P_GPS_STATE_Y, 		AHC_FALSE , OSDDraw_GPSStatus},
	{HDMI_GUI_DSC_VMD_STATE	, 	POS_ICON_HDMI_720P_VMD_X, 		POS_ICON_HDMI_720P_VMD_Y, 		AHC_TRUE , DrawCaptureMotionDtc},
	{0xFFFF}
};
#endif
#endif

UI_DARW_SET m_HdmiMovPBDraw_720P[] = 
{
	{HDMI_GUI_MOVPB_STATUS, 	POS_ICON_HDMI_720P_MOV_STATE_X, 		POS_ICON_HDMI_720P_MOV_STATE_Y, 		AHC_TRUE , DrawHdmiMoviePB_Status},
	{HDMI_GUI_MOVPB_FILE_INDEX, POS_ICON_HDMI_720P_MOV_FILEIDX_X, 	POS_ICON_HDMI_720P_MOV_FILEIDX_Y, 	AHC_TRUE , DrawHdmiMoviePB_FileIndex},
	{HDMI_GUI_MOVPB_UI_MODE	, 	POS_ICON_HDMI_720P_UI_MODE_X, 	POS_ICON_HDMI_720P_UI_MODE_Y,	AHC_FALSE, OSDDrawSetting_UIMode},
	{HDMI_GUI_MOVPB_SD_STATE, 	POS_ICON_HDMI_720P_MEDIA_X, 		POS_ICON_HDMI_720P_MEDIA_Y, 		AHC_FALSE, OSDDrawSetting_MediaType},
	{HDMI_GUI_MOVPB_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 		POS_ICON_HDMI_720P_BATT_Y, 		AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_MOVPB_VOL_BAR	, 	POS_ICON_HDMI_720P_SCENE_X, 		POS_ICON_HDMI_720P_SCENE_Y,		AHC_FALSE, NULL}, // TBD
	{HDMI_GUI_MOVPB_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 		POS_MOVPB_LOCK_FILE_Y, 		AHC_FALSE, DrawMovPb_LockCurFile},
	{HDMI_GUI_MOVPB_FILENAME , 	POS_ICON_HDMI_720P_MOV_NAME_X, 		POS_ICON_HDMI_720P_MOV_NAME_Y,		AHC_TRUE , DrawHdmiMoviePB_NameInfo},
	{HDMI_GUI_MOVPB_CUR_TIME, 	POS_ICON_HDMI_720P_MOV_CURTIME_X, 	POS_ICON_HDMI_720P_MOV_CURTIME_Y,		AHC_TRUE , DrawHdmiMoviePB_PlayInfo},
	{HDMI_GUI_MOVPB_TOTAL_TIME, POS_ICON_HDMI_720P_MOV_TOTALTIME_X, 	POS_ICON_HDMI_720P_MOV_TOTALTIME_Y, 	AHC_TRUE , DrawHdmiMoviePB_TotalTime},
	{0xFFFF}
};

#if (AUDIO_REC_PLAY_EN)
UI_DARW_SET m_HdmiAudPBDraw[] = 
{
	{HDMI_GUI_AUDPB_STATUS, 	POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE,  DrawAudPb_Status},
	{HDMI_GUI_AUDPB_FILE_INDEX, POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_FALSE, DrawAudPb_FileIndex},
	{HDMI_GUI_AUDPB_UI_MODE	, 	POS_ICON_HDMI_720P_UI_MODE_X,POS_ICON_HDMI_720P_UI_MODE_Y,AHC_FALSE, OSDDrawSetting_UIMode},
	{HDMI_GUI_AUDPB_SD_STATE, 	POS_ICON_HDMI_720P_MEDIA_X, 	POS_ICON_HDMI_720P_MEDIA_Y, 	AHC_FALSE, OSDDrawSetting_MediaType},
	{HDMI_GUI_AUDPB_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 	POS_ICON_HDMI_720P_BATT_Y, 	AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_AUDPB_VOL_BAR	, 	POS_ICON_HDMI_720P_SCENE_X, 	POS_ICON_HDMI_720P_SCENE_Y,	AHC_FALSE, NULL},
	{HDMI_GUI_AUDPB_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_FALSE, DrawAudPb_LockCurFile},
	{HDMI_GUI_AUDPB_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE,  DrawAudPb_FileInfo},
	{HDMI_GUI_AUDPB_CUR_TIME, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE,  DrawAudPb_PlayInfo},
	{HDMI_GUI_AUDPB_TOTAL_TIME, POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE,  DrawAudPb_TotalTime},
	{0xFFFF}
};
#endif

UI_DARW_SET m_HdmiJpgPBDraw_720P[] = 
{
	{HDMI_GUI_JPGPB_FILE_INDEX, POS_ICON_HDMI_720P_JPG_FILEIDX_X, 	POS_ICON_HDMI_720P_JPG_FILEIDX_Y, 	AHC_TRUE,  DrawHdmiPhotoPB_FileIndex},
	{HDMI_GUI_JPGPB_UI_MODE	, 	POS_ICON_HDMI_720P_UI_MODE_X, 	POS_ICON_HDMI_720P_UI_MODE_Y,	AHC_FALSE, OSDDrawSetting_UIMode},
	{HDMI_GUI_JPGPB_SD_STATE, 	POS_ICON_HDMI_720P_MEDIA_X, 		POS_ICON_HDMI_720P_MEDIA_Y, 		AHC_FALSE, OSDDrawSetting_MediaType},
	{HDMI_GUI_JPGPB_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 		POS_ICON_HDMI_720P_BATT_Y, 		AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{HDMI_GUI_JPGPB_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 		POS_JPGPB_LOCK_FILE_Y, 		AHC_FALSE, DrawJpgPb_LockCurFile},
	{HDMI_GUI_JPGPB_FILENAME , 	POS_ICON_HDMI_720P_JPG_NAME_X, 		POS_ICON_HDMI_720P_JPG_NAME_Y,		AHC_TRUE , DrawHdmiPhotoPB_NameInfo},
	{HDMI_GUI_JPGPB_FILEDATE , 	POS_ICON_HDMI_720P_JPG_FILEDATE_X, 	POS_ICON_HDMI_720P_JPG_FILEDATE_Y,	AHC_TRUE , DrawHdmiPhotoPB_DateInfo},
	{0xFFFF}
};
#endif // #if (HDMI_ENABLE)

#else   // _OEM_DRAW_

extern UI_DARW_SET m_VideoDraw[];
extern UI_DARW_SET m_DSCDraw[];
extern UI_DARW_SET m_BrowserDraw[];
extern UI_DARW_SET m_MovPBDraw[];
extern UI_DARW_SET m_AudPBDraw[];
extern UI_DARW_SET m_JpgPBDraw[];
extern UI_DARW_SET m_SlideDraw[];
extern UI_DARW_SET m_TVVideoDraw[];
extern UI_DARW_SET m_TVDSCDraw[];
extern UI_DARW_SET m_TVMovPBDraw[];
extern UI_DARW_SET m_TVAudPBDraw[];
extern UI_DARW_SET m_TVJpgPBDraw[];
extern UI_DARW_SET m_HdmiVideoDraw[];
extern UI_DARW_SET m_HdmiDSCDraw[];
extern UI_DARW_SET m_HdmiMovPBDraw[];
extern UI_DARW_SET m_HdmiAudPBDraw[];
extern UI_DARW_SET m_HdmiJpgPBDraw[];

#endif // #ifndef _OEM_DRAW_

/*===========================================================================
 * Main body 
 *===========================================================================*/ 

void UIDrawVideoFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
	UINT8 i;

	for (i = 0; m_VideoDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_VideoDraw[i].m_BlockID == idx)
		{
			if ((m_VideoDraw[i].m_Enable == AHC_TRUE) && (m_VideoDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_VideoDraw[i].m_DrawFunc(ubID, m_VideoDraw[i].m_PosX, m_VideoDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_VideoDraw[i].m_DrawFunc(ubID, m_VideoDraw[i].m_PosX, m_VideoDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}
}

void UIDrawDSCFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (DSC_MODE_ENABLE)

	UINT8 i;

	for (i = 0; m_DSCDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_DSCDraw[i].m_BlockID == idx)
		{
			if ((m_DSCDraw[i].m_Enable == AHC_TRUE) && (m_DSCDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_DSCDraw[i].m_DrawFunc(ubID, m_DSCDraw[i].m_PosX, m_DSCDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_DSCDraw[i].m_DrawFunc(ubID, m_DSCDraw[i].m_PosX, m_DSCDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif	
}

void UIDrawBrowserFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
	UINT8 i;

	for (i = 0; m_BrowserDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_BrowserDraw[i].m_BlockID == idx)
		{
			if ((m_BrowserDraw[i].m_Enable == AHC_TRUE) && (m_BrowserDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_BrowserDraw[i].m_DrawFunc(ubID, m_BrowserDraw[i].m_PosX, m_BrowserDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_BrowserDraw[i].m_DrawFunc(ubID, m_BrowserDraw[i].m_PosX, m_BrowserDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}
}

void UIDrawMovPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
	UINT8 i;

	for (i = 0; m_MovPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_MovPBDraw[i].m_BlockID == idx)
		{
			if ((m_MovPBDraw[i].m_Enable == AHC_TRUE) && (m_MovPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_MovPBDraw[i].m_DrawFunc(ubID, m_MovPBDraw[i].m_PosX, m_MovPBDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_MovPBDraw[i].m_DrawFunc(ubID, m_MovPBDraw[i].m_PosX, m_MovPBDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}
}

void UIDrawAudPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (AUDIO_REC_PLAY_EN)

	UINT8 i;

	for (i = 0; m_AudPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_AudPBDraw[i].m_BlockID == idx)
		{
			if ((m_AudPBDraw[i].m_Enable == AHC_TRUE) && (m_AudPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_AudPBDraw[i].m_DrawFunc(ubID, m_AudPBDraw[i].m_PosX, m_AudPBDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_AudPBDraw[i].m_DrawFunc(ubID, m_AudPBDraw[i].m_PosX, m_AudPBDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif
}

void UIDrawJpgPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
	UINT8 i;

	for (i = 0; m_JpgPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_JpgPBDraw[i].m_BlockID == idx)
		{
			if ((m_JpgPBDraw[i].m_Enable == AHC_TRUE) && (m_JpgPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_JpgPBDraw[i].m_DrawFunc(ubID, m_JpgPBDraw[i].m_PosX, m_JpgPBDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_JpgPBDraw[i].m_DrawFunc(ubID, m_JpgPBDraw[i].m_PosX, m_JpgPBDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}
}

void UIDrawSlideFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (SLIDESHOW_EN)

	UINT8 i;

	for (i = 0; m_SlideDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_SlideDraw[i].m_BlockID == idx)
		{
			if ((m_SlideDraw[i].m_Enable == AHC_TRUE) && (m_SlideDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_SlideDraw[i].m_DrawFunc(ubID, m_SlideDraw[i].m_PosX, m_SlideDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_SlideDraw[i].m_DrawFunc(ubID, m_SlideDraw[i].m_PosX, m_SlideDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif	
}

#if 0
void ____TV_Drawing_Function_____(){ruturn;} // dummy
#endif

void UIDrawTV_VideoFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (TVOUT_ENABLE) && (TVOUT_PREVIEW_EN)

	UINT8 i;

	for (i = 0; m_TVVideoDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_TVVideoDraw[i].m_BlockID == idx)
		{
			if ((m_TVVideoDraw[i].m_Enable == AHC_TRUE) && (m_TVVideoDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_TVVideoDraw[i].m_DrawFunc(ubID, m_TVVideoDraw[i].m_PosX, m_TVVideoDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_TVVideoDraw[i].m_DrawFunc(ubID, m_TVVideoDraw[i].m_PosX, m_TVVideoDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif	
}

void UIDrawTV_DSCFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (TVOUT_ENABLE) && (TVOUT_PREVIEW_EN) && (DSC_MODE_ENABLE)

	UINT8 i;

	for (i = 0; m_TVDSCDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_TVDSCDraw[i].m_BlockID == idx)
		{
			if ((m_TVDSCDraw[i].m_Enable == AHC_TRUE) && (m_TVDSCDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_TVDSCDraw[i].m_DrawFunc(ubID, m_TVDSCDraw[i].m_PosX, m_TVDSCDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_TVDSCDraw[i].m_DrawFunc(ubID, m_TVDSCDraw[i].m_PosX, m_TVDSCDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif
}

void UIDrawTV_MovPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (TVOUT_ENABLE)

	UINT8 i;

	for (i = 0; m_TVMovPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_TVMovPBDraw[i].m_BlockID == idx)
		{
			if ((m_TVMovPBDraw[i].m_Enable == AHC_TRUE) && (m_TVMovPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_TVMovPBDraw[i].m_DrawFunc(ubID, m_TVMovPBDraw[i].m_PosX, m_TVMovPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_TVMovPBDraw[i].m_DrawFunc(ubID, m_TVMovPBDraw[i].m_PosX, m_TVMovPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif
}

void UIDrawTV_AudPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (TVOUT_ENABLE) && (AUDIO_REC_PLAY_EN)

	UINT8 i;

	for (i = 0; m_TVAudPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_TVAudPBDraw[i].m_BlockID == idx)
		{
			if ((m_TVAudPBDraw[i].m_Enable == AHC_TRUE) && (m_TVAudPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_TVAudPBDraw[i].m_DrawFunc(ubID, m_TVAudPBDraw[i].m_PosX, m_TVAudPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_TVAudPBDraw[i].m_DrawFunc(ubID, m_TVAudPBDraw[i].m_PosX, m_TVAudPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif	
}

void UIDrawTV_JpgPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (TVOUT_ENABLE)

	UINT8 i;

	for (i = 0; m_TVJpgPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_TVJpgPBDraw[i].m_BlockID == idx)
		{
			if ((m_TVJpgPBDraw[i].m_Enable == AHC_TRUE) && (m_TVJpgPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_TVJpgPBDraw[i].m_DrawFunc(ubID, m_TVJpgPBDraw[i].m_PosX, m_TVJpgPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_TVJpgPBDraw[i].m_DrawFunc(ubID, m_TVJpgPBDraw[i].m_PosX, m_TVJpgPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif
}

#if 0
void ____HDMI_Drawing_Function_____(){ruturn;} // dummy
#endif

void UIDrawHdmi_VideoFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (HDMI_ENABLE) && (HDMI_PREVIEW_EN)

	UINT8 i;
	UI_DARW_SET	*m_HdmiVideoDraw;
		
	if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P)
	{
		m_HdmiVideoDraw = (UI_DARW_SET *)m_HdmiVideoDraw_1080P;
	}
	else
	{
		m_HdmiVideoDraw = (UI_DARW_SET *)m_HdmiVideoDraw_720P;
	}		
	
	for (i = 0; m_HdmiVideoDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_HdmiVideoDraw[i].m_BlockID == idx)
		{
			if ((m_HdmiVideoDraw[i].m_Enable == AHC_TRUE) && (m_HdmiVideoDraw[i].m_DrawFunc != NULL))
			{
			#if OSD_PREVIEW_SCALE_HDMI
				if (bClear)
					m_HdmiVideoDraw[i].m_DrawFunc(ubID, m_HdmiVideoDraw[i].m_PosX, m_HdmiVideoDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);
				
				if (bShow)
					m_HdmiVideoDraw[i].m_DrawFunc(ubID, m_HdmiVideoDraw[i].m_PosX, m_HdmiVideoDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			#else
				
				if (bClear)
					m_HdmiVideoDraw[i].m_DrawFunc(ubID, m_HdmiVideoDraw[i].m_PosX, m_HdmiVideoDraw[i].m_PosY, LARGE_SIZE, MAG_3X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_HdmiVideoDraw[i].m_DrawFunc(ubID, m_HdmiVideoDraw[i].m_PosX, m_HdmiVideoDraw[i].m_PosY, LARGE_SIZE, MAG_3X, AHC_TRUE, bkColor, Para1);
			#endif	
			}
		}
	}

#endif
}

void UIDrawHdmi_DSCFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (HDMI_ENABLE) && (HDMI_PREVIEW_EN) && (DSC_MODE_ENABLE)

	UINT8 i;
    
	UI_DARW_SET	*m_HdmiDSCDraw;
		
	if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P)
	{
		m_HdmiDSCDraw = (UI_DARW_SET *)m_HdmiDSCDraw_1080P;
	}
	else
	{
		m_HdmiDSCDraw = (UI_DARW_SET *)m_HdmiDSCDraw_720P;
	}	
	    
	for (i = 0; m_HdmiDSCDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_HdmiDSCDraw[i].m_BlockID == idx)
		{
			if ((m_HdmiDSCDraw[i].m_Enable == AHC_TRUE) && (m_HdmiDSCDraw[i].m_DrawFunc != NULL))
			{
			#if OSD_PREVIEW_SCALE_HDMI
				if (bClear)
					m_HdmiDSCDraw[i].m_DrawFunc(ubID, m_HdmiDSCDraw[i].m_PosX, m_HdmiDSCDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);
				
				if (bShow)
					m_HdmiDSCDraw[i].m_DrawFunc(ubID, m_HdmiDSCDraw[i].m_PosX, m_HdmiDSCDraw[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			#else
				if (bClear)
					m_HdmiDSCDraw[i].m_DrawFunc(ubID, m_HdmiDSCDraw[i].m_PosX, m_HdmiDSCDraw[i].m_PosY, LARGE_SIZE, MAG_3X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_HdmiDSCDraw[i].m_DrawFunc(ubID, m_HdmiDSCDraw[i].m_PosX, m_HdmiDSCDraw[i].m_PosY, LARGE_SIZE, MAG_3X, AHC_TRUE, bkColor, Para1);
			#endif	
			}
		}
	}

#endif
}

void UIDrawHdmi_MovPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (HDMI_ENABLE)

	UINT8 i;
	UI_DARW_SET	*m_HdmiMovPBDraw;
	
	if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P)
	{
		m_HdmiMovPBDraw = (UI_DARW_SET *)m_HdmiMovPBDraw_1080P;
	}
	else
	{
		m_HdmiMovPBDraw = (UI_DARW_SET *)m_HdmiMovPBDraw_720P;
	}
	
	for (i = 0; m_HdmiMovPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_HdmiMovPBDraw[i].m_BlockID == idx)
		{
			if ((m_HdmiMovPBDraw[i].m_Enable == AHC_TRUE) && (m_HdmiMovPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_HdmiMovPBDraw[i].m_DrawFunc(ubID, m_HdmiMovPBDraw[i].m_PosX, m_HdmiMovPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_HdmiMovPBDraw[i].m_DrawFunc(ubID, m_HdmiMovPBDraw[i].m_PosX, m_HdmiMovPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif
}

void UIDrawHdmi_AudPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (HDMI_ENABLE) && (AUDIO_REC_PLAY_EN)

	UINT8 i;

	for (i = 0; m_HdmiAudPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_HdmiAudPBDraw[i].m_BlockID == idx)
		{
			if ((m_HdmiAudPBDraw[i].m_Enable == AHC_TRUE) && (m_HdmiAudPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_HdmiAudPBDraw[i].m_DrawFunc(ubID, m_HdmiAudPBDraw[i].m_PosX, m_HdmiAudPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_HdmiAudPBDraw[i].m_DrawFunc(ubID, m_HdmiAudPBDraw[i].m_PosX, m_HdmiAudPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif	
}

void UIDrawHdmi_JpgPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (HDMI_ENABLE)

	UINT8 i;
	UI_DARW_SET	*m_HdmiJpgPBDraw;
	
	if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P)
	{
		m_HdmiJpgPBDraw = (UI_DARW_SET *)m_HdmiJpgPBDraw_1080P;
	}
	else
	{
		m_HdmiJpgPBDraw = (UI_DARW_SET *)m_HdmiJpgPBDraw_720P;
	}	

	for (i = 0; m_HdmiJpgPBDraw[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_HdmiJpgPBDraw[i].m_BlockID == idx)
		{
			if ((m_HdmiJpgPBDraw[i].m_Enable == AHC_TRUE) && (m_HdmiJpgPBDraw[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_HdmiJpgPBDraw[i].m_DrawFunc(ubID, m_HdmiJpgPBDraw[i].m_PosX, m_HdmiJpgPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_HdmiJpgPBDraw[i].m_DrawFunc(ubID, m_HdmiJpgPBDraw[i].m_PosX, m_HdmiJpgPBDraw[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif
}